# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # NPM dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    # Allow both direct and indirect (transitive) dependency updates
    allow:
      - dependency-type: "all"
    # Ignore major version updates for stable packages
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sequelize"
        update-types: ["version-update:semver-major"]
      - dependency-name: "prosemirror-*"
        update-types: ["version-update:semver-major"]
    # Group related dependencies
    groups:
      # Group all babel packages
      babel:
        patterns:
          - "@babel/*"
          - "babel-*"
      # Group all sentry packages
      sentry:
        patterns:
          - "@sentry/*"
      # Group all font awesome packages
      fortawesome:
        patterns:
          - "@fortawesome/*"
      # Group all AWS SDK packages
      aws:
        patterns:
          - "@aws-sdk/*"
          - "aws-sdk"
      # Group testing libraries
      testing:
        patterns:
          - "jest"
          - "@types/jest"
          - "@testing-library/*"
          - "jest-*"
      # Group React ecosystem
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      # Group TypeScript and related
      typescript:
        patterns:
          - "typescript"
          - "@types/*"
          - "ts-*"
      # Group ESLint and plugins
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@typescript-eslint/*"
      # Group Vite and plugins
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
          - "vite-*"
    # Add labels to PRs
    labels:
      - "dependencies"
      - "automated"
      - "automerge"
    # Prefix commit messages
    commit-message:
      prefix: "chore"
      include: "scope"
  
  # Docker base image updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "docker"
      - "automated"
      - "automerge"
    commit-message:
      prefix: "chore"
      include: "scope"
  
  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
      - "automerge"
    commit-message:
      prefix: "chore"
      include: "scope"
